mission:
  frame_id: world
  waypoint_reached_radius: 1.0
  waypoints:
    - name: wp0
      x: 40.0
      y: 0.0
      z: 1.5
    - name: wp1
      x: -13.0
      y: -17.0
      z: 1.5
    - name: wp2
      x: -14.0
      y: 13.0
      z: 1.5
    - name: wp3
      x: 30.0
      y: 0.0
      z: 1.5
